### ISSUE TITLE
Support GitHub's preview mergebox ("new merge experience")

### ISSUE THREAD

**Issue by MattSturgeon** [Mergifyio/browser-extension#29]
## Expected Behavior

The extension to add UI elements to the mergebox

<details><summary>Screenshot with non-preview mergebox</summary>
<p>

![image](https://github.com/user-attachments/assets/59df6938-410f-4bf1-aea7-7c180f6173b4)

</p>
</details> 

## Actual Behavior

No UI elements appear

<details><summary>Screenshot with new preview mergebox</summary>
<p>

![image](https://github.com/user-attachments/assets/2bd1a4bb-02e9-4fb3-8546-423689e58f80)

</p>
</details> 

## Steps to Reproduce the Problem

  1. Enable firefox [Mergify AddOn](https://addons.mozilla.org/en-US/firefox/addon/mergify/)
  2. Enable "Try the new merge experience" (can be done with `?new_mergebox=true`)
  3. Observe UI elements no longer appear
  4. :cry: 

## Specifications

  - Pull Request URL:
  - Mergify Config URL:

**Comment by MattSturgeon** [comment]
<details><summary>HTML tree with mergify UI elements</summary>
<p>

![image](https://github.com/user-attachments/assets/166a8f18-11e4-416c-bd6c-92554d2e5862)


</p>
</details> 

<details><summary>HTML tree for the new preview mergebox</summary>
<p>

![image](https://github.com/user-attachments/assets/d4679196-d614-438e-aae7-585dcdaed04c)


</p>
</details>

**Comment by DouglasBlackwood** [comment]
Hi! It's on our roadmap. I'll keep you updated once it's released.

**Comment by DouglasBlackwood** [comment]
Hi! We are releasing the browser extension 1.0.14. You should see the action buttons soon.

**Comment by MattSturgeon** [comment]
> Hi! We are releasing the browser extension 1.0.14. You should see the action buttons soon.

Hm, I've just updated to 1.0.14 and restarted my browser, but I still can't see the buttons.

Stepping through `tryInject()`, it seems the issue is that `isMergifyEnabledOnTheRepo` is null. A breakpoint on [line L224](https://github.com/Mergifyio/browser-extension/blob/ad825b0ad47a00d8b6f91a0a3e98fd7442951e50/src/mergify.js#L224) is never hit.

I can confirm that `document.querySelector('a[href="/apps/mergify"]')` is null when the new mergebox is enabled.

With the new mergebox **_disabled_** it exists: 
![image](https://github.com/user-attachments/assets/438e61b7-fdc6-43f7-8e1b-a36430632204)

The **_equivalent_** image in the new mergebox looks like:

```html
<img data-component="Avatar"
     class="flex-shrink-0 ml-2 mr-2 prc-Avatar-Avatar-ZRS-m"
     alt="Summary"
     data-square=""
     width="20"
     height="20"
     style="--avatarSize-regular: 20px;"
     src="https://avatars.githubusercontent.com/in/10562?s=40&amp;v=4"
     data-testid="github-avatar">
```

But it is not wrapped in an `<a>` tag:
![image](https://github.com/user-attachments/assets/16e69add-6ffb-40ef-9e22-0f64cd24ff36)
