### ISSUE TITLE
Mergify buttons can be injected into PR commits tab

### ISSUE THREAD

**Issue by MattSturgeon** [Mergifyio/browser-extension#33]
## Expected Behavior

No buttons are shown on the PR's "commits" tab

## Actual Behavior

![image](https://github.com/user-attachments/assets/05595d31-e47a-419d-97d8-8e0f1aa76895)

![image](https://github.com/user-attachments/assets/59460e54-4ee1-453f-b06b-66b840308ab0)

## Steps to Reproduce the Problem

~~Visit https://github.com/nix-community/nixvim/pull/2732/commits~~

EDIT: I can't seem to reproduce this after reloading, but I definitely encountered it just now.

## Specifications

  - Pull Request URL: https://github.com/nix-community/nixvim/pull/2732
  - Mergify Config URL: https://github.com/nix-community/nixvim/blob/main/.github/mergify.yml

**Comment by MattSturgeon** [comment]
Randomly reproduced this again:
![image](https://github.com/user-attachments/assets/c7a13195-5f86-45a9-9d5b-edc64d4769b0)

It happened again when refreshing once, but refreshing again or opening [the PR](https://github.com/nix-community/nixvim/pull/2738/commits) in another tab did not reproduce the issue.

**Comment by DouglasBlackwood** [comment]
Version 1.0.16 should be released soon!
